name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2, build image, and run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/project/aws-docker-app

            git pull origin main
            
            sudo docker stop learn-docker-deployment || true
            sudo docker rm learn-docker-deployment || true
            
            sudo docker build -t learn-docker-deployment:latest .
            sudo docker run -d -p 80:8080 --name learn-docker-deployment learn-docker-deployment:latest
